Problem Statement 2: 
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 
The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
i 1 2 3 4 5 6 7 8 9 10 
===== == == == == == == == == == == 

Input 10 20 30 40 50 60 70 80 90 100  
y1 25 = (10+20+30+40)/4 
y2 35 = (20+30+40+50)/4 
y3 45 = (30+40+50+60)/4 
y4 55 = (40+50+60+70)/4 
y5 65 = (50+60+70+80)/4 
y6 75 = (60+70+80+90)/4 
y7 85 = (70+80+90+100)/4 

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [2]:
import numpy as np

In [11]:
a = np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
a

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [12]:
b = np.sort(a)
b

array([  2,   3,   5,   7,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [13]:
# Function
def moving_avg(array,k):
    for i in range((array.size)-k+1):
        sum = 0
        for j in range(k):
            sum = sum + array[i+j]
        sum1 = sum/k
        print(sum1)

In [14]:
# Moving average of the given array above:
moving_avg(a,3)

5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333


In [15]:
# Moving average over the sorted array:
moving_avg(b,3)

3.3333333333333335
5.0
6.666666666666667
8.333333333333334
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333


In [16]:
# Moving average of the given example above:
c = np.array([10,20,30,40,50,60,70,80,90,100])
moving_avg(c,4)

25.0
35.0
45.0
55.0
65.0
75.0
85.0


Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input vector. 

The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 

HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [16]:
# 1d Input array
d = np.array([1,2,3,5,7])
d

array([1, 2, 3, 5, 7])

In [17]:
def vander(array,N=0):
    l = []
    if N==0:
        N=len(array)
    for i in range(N):
        a = pow(array,N-i-1)
        l.append(a)
    c = np.array(l).T
    return c

In [18]:
vander(d,N=3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1],
       [49,  7,  1]], dtype=int32)

In [19]:
vander(d,N=4)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1],
       [343,  49,   7,   1]], dtype=int32)

In [20]:
vander(d)

array([[   1,    1,    1,    1,    1],
       [  16,    8,    4,    2,    1],
       [  81,   27,    9,    3,    1],
       [ 625,  125,   25,    5,    1],
       [2401,  343,   49,    7,    1]], dtype=int32)